mysite/cointoss/urls.py
from django.urls import path
from . import views

app_name = 'cointoss'
urlpatterns = [
    path('', views.cointoss_index, name='cointoss_index'),
    path('results/', views.cointoss_results, name='cointoss_results'),
]

mysite/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_index, name='home_index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rps/', include('rps.urls')),
    path('', include('home.urls')),
    path('cointoss/', include('cointoss.urls')),


]

mysite/rps/urls.py
from django.urls import path
from . import views

app_name = 'rps'
urlpatterns = [
    path('', views.rps_index, name='rps_index'),
    path('results/', views.rps_results, name='rps_results'),
]

mysite/cointoss/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.


class Cointoss_Results(models.Model):
    game_name = models.CharField(max_length=200, default="cointoss")
    total_cointoss_initiated = models.BigIntegerField(default=0)
    total_heads_count = models.BigIntegerField(default=0)
    total_tails_count = models.BigIntegerField(default=0)
    total_round_count = models.BigIntegerField(default=0)

    def __str__(self):
        return str(self.id)
        # return self.game_name

    # def total_rps_initiated2(self):
    #     # return self.total_rps_initiated
    #     return '{0} ({1})'.format(self.id, self.total_rps_initiated, self.total_round_count)

    # def total_game_count(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # was_published_recently.admin_order_field = 'pub_date'
    # was_published_recently.boolean = True
    # was_published_recently.short_description = 'Published recently?'

# Create your models here.

    # Metadata
    # class Meta:
        # ordering = ["-my_field_name"]
    # Methods

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/rps/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.


class RPS_Results(models.Model):
    game_name = models.CharField(max_length=200, default="rps")
    total_rps_initiated = models.BigIntegerField(default=0)
    total_round_count = models.BigIntegerField(default=0)
    total_rock_count = models.BigIntegerField(default=0)
    total_paper_count = models.BigIntegerField(default=0)
    total_scissors_count = models.BigIntegerField(default=0)
    rps_yay_count = models.BigIntegerField(default=0)
    rps_nay_count = models.BigIntegerField(default=0)

    def __str__(self):
        return str(self.id)
        # return self.game_name

    def total_rps_initiated2(self):
        # return self.total_rps_initiated
        return '{0} ({1})'.format(self.id, self.total_rps_initiated, self.total_round_count)

    # def total_game_count(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # was_published_recently.admin_order_field = 'pub_date'
    # was_published_recently.boolean = True
    # was_published_recently.short_description = 'Published recently?'

# Create your models here.

    # Metadata
    # class Meta:
        # ordering = ["-my_field_name"]
    # Methods

mysite/cointoss/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from cointoss.game_cointoss import *
from .models import Cointoss_Results

# Create your views here.


def cointoss_index(request):
    rounds = [1, 3, 5, 7]
    return render(request, 'cointoss/index.html', {'rounds': rounds})


def cointoss_results(request):
    # if "rounds" in request.POST:
    r = request.POST['rounds']
    d1 = request.POST['decision1']
    rounds = int(r)
    list_result, heads_win_count, tails_win_count = cointoss_game(rounds)

    cointoss_stats = Cointoss_Results.objects.get(game_name='cointoss')
    cointoss_stats.total_cointoss_initiated += 1
    cointoss_stats.total_round_count += rounds
    cointoss_stats.total_heads_count += heads_win_count
    cointoss_stats.total_tails_count += tails_win_count

    if heads_win_count > tails_win_count:
        yay_or_nay = 'Yay'
    else:
        yay_or_nay = 'Nay'

    cointoss_stats.save()

    return render(request, 'cointoss/results.html', {'list_result': list_result, 'd1': d1, 'heads_win_count': heads_win_count, 'tails_win_count': tails_win_count})

mysite/home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# from django.views import generic
# from django.utils import timezone
# from rps.game_rps import *

# Create your views here.


def home_index(request):
    return render(request, 'home/index.html')

mysite/rps/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from rps.game_rps import *
from .models import RPS_Results

#from chat.consumers import *


# Create your views here.


def rps_index(request):
    rounds = [1, 3, 5, 7]
    return render(request, 'rps/index.html', {'rounds': rounds})


def rps_results(request):
    # if "rounds" in request.POST:
    r = request.POST['rounds']
    rounds = int(r)
    d1 = request.POST['decision1']
    #d2 = request.POST['decision2']
    list_result, d1_win_count, d2_win_count = rps_game(rounds)

    rps_stats = RPS_Results.objects.get(game_name='rps')
    rps_stats.total_rps_initiated += 1

    temp_total_round_count = len(list_result)
    rps_stats.total_round_count += temp_total_round_count

    temp_list_result = [num for elem in list_result for num in elem]
    temp_rock_count = temp_list_result.count('Rock')
    temp_paper_count = temp_list_result.count('Paper')
    temp_scissors_count = temp_list_result.count('Scissors')

    rps_stats.total_rock_count += temp_rock_count
    rps_stats.total_paper_count += temp_paper_count
    rps_stats.total_scissors_count += temp_scissors_count

    if d1_win_count > d2_win_count:
        yay_or_nay = 'Yay'
        rps_stats.rps_yay_count += 1
        # chat.consumers.receive("rock")

    else:
        yay_or_nay = 'Nay'
        rps_stats.rps_nay_count += 1

    rps_stats.save()

    return render(request, 'rps/results.html', {'list_result': list_result, 'd1': d1, 'd1_win_count': d1_win_count, 'd2_win_count': d2_win_count})

mysite/cointoss/templates/cointoss/index.html
{% extends 'home/navbar.html' %} {% block content %}

<div class="container">
    <form action="{% url 'cointoss:cointoss_results' %}" method="post">
        {% csrf_token %} Decision on:
        <input type="text" name="decision1">
        <br> Number of rounds:
        <select name="rounds"> {% for q in rounds %}
            <option value="{{ q }}" name="q">Best of {{ q }} </option>
            {% endfor %}
        </select>
        <br>
        <br>
        <input type="submit" value="Submit" />
    </form>


    {% endblock %}

</div>

mysite/cointoss/templates/cointoss/results.html
 {% extends 'home/navbar.html' %} {% block content %}

<div class="container">
    <h1>Results: {% if heads_win_count > tails_win_count %} Yay {% else %} Nay {% endif %}


    </h1>
    Decision on: {{ d1 }}

    <br>
    <br>



    <table class="table table-striped table-responsive w-auto">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Coin Toss</th>
                <!-- <th scope="col">Decision 2</th>
                <th scope="col">Result</th> -->
            </tr>
        </thead>

        <tbody>
            {% for x in list_result %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ x }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

    Yay: {{ heads_win_count }} vs Nay: {{ tails_win_count }}
    </p>
    {% endblock %}

</div>

mysite/home/templates/home/index.html
{% extends 'home/navbar.html' %} {% block content %}

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">Yay or Nay?</h1>
            <p>Use simple games to make decisions.
            </p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h4>Rock-Paper-Scissors</h4>
                <p>Simple game of Rock-Paper-Scissors.</p>
                <p>
                    <a class="btn btn-secondary" href={% url 'rps:rps_index' %} role="button">Let's Play &raquo;</a>
                </p>
            </div>
            <div class="col-md-4">
                <h4>Coin Toss</h4>
                <p>Flip a coin to decide.</p>
                <p>
                    <a class="btn btn-secondary" href={% url 'cointoss:cointoss_index' %} role="button">Let's Play &raquo;</a>
                </p>
            </div>
        </div>

        <hr>

    </div>
    <!-- /container -->

</main>

{% endblock %}

mysite/home/templates/home/navbar.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Decision Games</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/jumbotron/jumbotron.css" rel="stylesheet">

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home:home_index' %}">Yay Nay</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <!-- 
                    <li class="{% ifequal request.path '/' %} nav-item active {% endifequal %}">
                        <a class="nav-link" href={% url 'home:home_index' %}>Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item"> -->
                    <li class="{% ifequal request.path '/rps/' %} nav-item active {% endifequal %}">
                        <a class="nav-link" href={% url 'rps:rps_index' %}>Rock-Paper-Scissors</a>
                    </li>
                    <li class="{% ifequal request.path '/cointoss/' %} nav-item active {% endifequal %}">
                        <a class="nav-link" href={% url 'cointoss:cointoss_index' %}>Coin Toss</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %} {% endblock %}


    <footer class="container">
        <!-- <p>&copy; Company 2017-2018</p> -->
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</body>

</html>

mysite/rps/templates/rps/detail.html
<!-- 
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}" />
-->


<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">

<!-- Custom styles for this template -->
<link href="https://getbootstrap.com/docs/4.1/examples/jumbotron/jumbotron.css" rel="stylesheet">

<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>
    <strong>{{ error_message }}</strong>
</p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %} {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br /> {% endfor %}
    <input type="submit" value="Vote" />
</form>

mysite/rps/templates/rps/index.html
{% extends 'home/navbar.html' %} {% block content %}

<div class="container">
    <form action="{% url 'rps:rps_results' %}" method="post">
        {% csrf_token %} Decision on:
        <input type="text" name="decision1">
        <br> Number of rounds:
        <select name="rounds"> {% for q in rounds %}
            <option value="{{ q }}" name="q">Best of {{ q }} </option>
            {% endfor %}
        </select>
        <br>
        <br>
        <input type="submit" value="Submit" />
    </form>


    {% endblock %}

</div>

mysite/rps/templates/rps/index2.html
<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">

<!-- Custom styles for this template -->
<link href="https://getbootstrap.com/docs/4.1/examples/jumbotron/jumbotron.css" rel="stylesheet">

<form action="{% url 'rps:rps_results' %}" method="post">
    {% csrf_token %} Decision 1:
    <input type="text" name="decision1">
    <br> Decision 2:
    <input type="text" name="decision2">
    <br> Number of rounds:
    <select name="rounds"> {% for q in rounds %}
        <option value="{{ q }}" name="q">{{ q }} </option>
        {% endfor %}
    </select>
    <br>
    <br>
    <input type="submit" value="Submit" />
</form>

mysite/rps/templates/rps/results.html
 {% extends 'home/navbar.html' %} {% block content %}

<div class="container">
    <h1>Results: {% if d1_win_count > d2_win_count %} Yay {% else %} Nay {% endif %}


    </h1>
    Decision on: {{ d1 }}
    <br>

    <br>


    <table class="table table-striped table-responsive w-auto">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Yay</th>
                <th scope="col">Nay</th>
                <th scope="col">Result</th>
            </tr>
        </thead>

        <tbody>
            {% for x, y, z in list_result %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ x }}</td>
                <td>{{ y }}</td>
                <td>{{ z }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    Yay: {{ d1_win_count }} vs Nay: {{ d2_win_count }}
    </p>
    <br> {% if d1_win_count > d2_win_count %}
    <!-- <p>Decision 1: {{ d1 }} Wins! {% else %}
        <p> 2: {{ d2 }} Wins! {% endif %} {% endblock %}
        -->
</div>

mysite/rps/templates/rps/results2.html
<h1>

    Results</h1>
{{ d1 }}
<br> {{ d2 }}
<br>

<br> {% for i in list_result %} {{ i }}

<br> {% endfor %}

<br>
<br> {% if d1_win_count > d2_win_count %}
<p>Decision 1: {{ d1 }} Wins!
    <br> {{ d1_win_count }} vs {{ d2_win_count }}</p>

{% else %}
<p>Decision 2: {{ d2 }} Wins!
    <br> {{ d2_win_count }} vs {{ d1_win_count }}</p>

{% endif %}